### PR TITLE
Don't build 4GB images, build images as big as the required contents.

### PR DESCRIPTION
**Pull request by vorlonofportland**
snappy supports auto resizing of the root partition on first boot, so we
don't need to preallocate space.  This makes it faster to write the image to
a disk (we already use sparseness everywhere else to ensure fast writes),
and avoids problems with media that is slightly below the nominal size.

This change:

 - fixes _calculate_dirsize() to always return an integer (rounding up)
 - adds explicit padding for ext4 metadata (so we never try to use a size
   of 0 for our partition when we have no initial files to create)
 - fine-tunes the requirements for the backup GPT space, which previously
   worked more or less by accident
 - does not require the rootfs to be an even multiple of 1MiB, since aligned
   reads don't matter nearly so much at the end of the disk and we'll be
   resized to use whatever space is available anyway so it's short-lived.

### CODE REVIEW

**Comment by mvo5** [comment]
One thing to consider here is that this makes it harder to use the image directly inside qemu/kvm or experimenting/development. Unless I miss something there will be (almost?) no free space so that the first snap install will result in a out-of-diskspace error.

**Comment by ogra1** [comment]
http://paste.ubuntu.com/23181304/ has a quick-hack workaround ... though long term we probably want an actual --size or --minsize option

**Comment by ogra1** [comment]
hmm, or not ... seems this iis the wrong place to inject the size

**Comment by ogra1** [comment]
equally ugly, but now working :) http://paste.ubuntu.com/23181669/

**Pull request merged**
