### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by warsaw**
This improves the code in two ways.

* It uses the python3-voluptuous package to do simple syntactic validation of the image.yaml file.  It can't do interdependent sanity checks (e.g. no fs-type allowed for role ESP), but those are fairly easy to post-process.  It also makes coercing data types nicer, especially when those keys are optional.  The YAML spec will change, and thus so will the schema, but I think this prove that voluptuous can make things nicer.

* Adds support for [LP: #1605434](https://bugs.launchpad.net/ubuntu-image/+bug/1605434) by allowing you to set the UBUNTUIMAGE_MOCK_SNAP envar to cache the results of `snap weld` when the model assertion and channel are the same.  Really there are only two such calls in the test suite right now, but it does at least halve the local test suite run time for me, so win!

On the latter: right now the envar is binary; if it's set then `snap weld` is called once and the results cached.  If it's not set then it's called every time.  I could imagine a third option that would avoid calling it at all and just using sample data.

Also, the default is to call `snap weld` every time, but the .travis-ci.yml file sets the envar.

I wonder if we should mock `snap weld` by default?  Then you'd set the envar (probably renamed) to disable the mocking.

This branch also contains some of Steve's original code.

### CODE REVIEW

**Comment by warsaw** [comment]
One other potential caveat.  This does use the file name of the model assertion in the cache directory name as described in the Launchpad bug.  That's not really the best way to determine uniqueness; instead we should be hashing the contents of the model.assertion file.  I might do that before merging this branch.

**Comment by warsaw** [comment]
Okay, using the hash was an easy change so I did that.

@vorlonofportland if you have any opinions on the semantics of $UBUNTUIMAGE_MOCK_SNAP, speak now or forever hold your tongue (where "forever" means no more than 10 minutes to land another branch).

**Comment by vorlonofportland** [comment]
strongly in favor of cache-by-default when running as part of the test suite.  For production use, there should obviously not be any caching by default; if you run 'ubuntu-image' a single time, it should make a single call to 'snap prepare-image' (weld) and this should not hit a cache.  If you are running 'ubuntu-image' more than once, we should not assume that any previously cached results are valid because time has elapsed and things may have changed store-side in a way that matters to us.  But for the test suite, "time elapsed between test cases and something changed on the store side" is uninteresting.

**Comment by warsaw** [comment]
As mentioned on Mumble, the `snap weld` results caching is only available during the test suite run because it's implement as part of the nose2 runner.  So +1 for enabling caching by default in the test suite, and running the `ubuntu-image` cli will never cache.  Set UBUNTUIMAGE_MOCK_SNAP to some falsey value (e.g. "0", "no", "false", "disable") to disable the caching.

**Pull request merged**
