### PR TITLE
Support for multi-volume gadgets

### PR DESCRIPTION
**Pull request by warsaw**
[LP: #1641727](https://bugs.launchpad.net/ubuntu-image/+bug/1641727)

Currently a work-in-progress, but I think the easy-ish refactoring path is going to work.  A lot of the tests need updating and I still don't have the multi-volume `--image-size` cli option plumbed in yet, but enough of the tests are working that I think this will be a fruitful direction.

### CODE REVIEW

**Comment by warsaw** [comment]
All the tests now pass, I think the last thing to do is to implement the `--image-size` cli changes from the LP bug.  Oh, and review/test!

**Comment by warsaw** [comment]
`debian/tests/mount` will need updating too.

**Comment by warsaw** [comment]
Last two (I think) to-dos:

* Add the `--image-size` options
* Fix the dep8 tests

**Comment by warsaw** [comment]
dep8 test update is all that's left

**Comment by warsaw** [comment]
I'd like to find or build a good sample gadget that defines multiple volumes, for the autopkgtests.  Other than that (and passing CI), this branch should be good to go.  Reviews welcome!

**Comment by warsaw** [comment]
7f11144 contains the source and instructions for creating a multi-volume gadget snap and a corresponding model assertion.  Use the instructions to turn the source into a local gadget snap, then use the model assertion to build the multi-volume images.  Three `.img` files will result.  The `pc.img` is uninteresting while the `hello.img` and `world.img` contain custom data that can be used to verify that multi-volume support works as expected.

The last step is to write an autopkgtest that uses the custom local gadget snap and model assertion, and verifies that these two extra image files are created and contain what they're supposed to contain.  That test shouldn't be difficult to write (it'll mostly be an adaptation of the `mount` test), but I'm EOW so that wont' happen today.

In the meantime, perhaps @sil2100 or @vorlonofportland would have some time to review the instructions for sanity?

**Comment by sil2100** [comment]
So far the changes look good. It's a really big diff so it takes a while to review, but so far I didn't see anything that could be a problem. I also created a single-volume image to see if all works correctly and the generated image was booting up correctly.

I know it's probably just an internal piece, but maybe the UBUNTU_IMAGE_PRESERVE_UNPACK env usage should be unit-tested as well? Looks like a useful thing. But yeah, I suppose it's more for developers so I wouldn't be worried.
I guess that's also the part that CI is actually yelling about in the coverage test.

Will be skimming through the code some more.

**Comment by warsaw** [comment]
Thanks for the review @sil2100.  I have actually added a unittest for the UBUNTU_IMAGE_PERSERVE_UNPACK code path and we now have 100% coverage again.  I've also added a multi-volume gadget.yaml autopkgtest.  The original mount test still tests image building for the single-volume official models.

I know the diff looks big but most of the changes are a refactoring (i.e. moving some code into loop-called private methods).  I do appreciate you looking it over!

Pushed all the commits that should cover this feature, so I consider the branch done, modulo other review comments you have.

**Pull request merged**
