### PR TITLE
Add a quick option to disable console-conf.

### PR DESCRIPTION
**Pull request by sil2100**
LP: #1866002

### CODE REVIEW

**Comment by sil2100** [comment]
Okay, tested this locally. The image built with --disable-console-conf went straight to the login prompt, where without it it starts console-conf as usual.

**Comment by xnox** [comment]
Please revert this as this is insecure implementation.

The point is to prevent people taking ownership of the device, and exposing full disk encrypted data under UC18.

This stamp file toggle is not enough to prevent the ability to launch console-conf.

As people with physical access can remove this stamp file from unencrypted writable, reprovision the device, launch console conf, and login as root when they are not supposed to have access to launch console-conf.

This should be a tamper proof way assertion to allow/dissalow console-conf this needs a key in the model assertion wether or not console-conf is allowed to operate by policy. As per security review from. Cape town.

**Comment by vorlonofportland** [comment]
Dimitri, this was implemented in response to https://bugs.launchpad.net/ubuntu/+source/ubuntu-image/+bug/1866002 which is not about having something "tamper-proof", but about having console-conf not get in the way of various other uses of the console on kiosk systems and remove the need for downstream workarounds.

In that light, why does this need to be reverted?

**Comment by xnox** [comment]
@vorlonofportland if those kiosks do not use full disk encryption, then this is fine.

I don't think this solution is sufficient on the full disk encrypted UC18 devices however, unless the stamp file and all of its sources are always encrypted (will double check with ondra on that).

**Pull request merged**
