### PR TITLE
Put options in some kind of sensible order in help output

### PR DESCRIPTION
**Pull request by vorlonofportland**
List common options first, debugging/developer options at the end

### CODE REVIEW

**Comment by mvo5** [comment]
:+1:

**Comment by warsaw** [comment]
Two things.  I don't believe that the order of options printed is officially defined to be the order in which `add_argument()` is called.  So this should be considered an [implementation detail](http://bugs.python.org/issue28219).  We could guard against that with a custom formatter class.

The other thought is that we may want to use argument groups to better organize the arguments.  One obvious group would be the state machine arguments `-u`, `-t`, and `-r` (those are in a mutually exclusive group right now, but that doesn't translate to a group name and description).

I'd probably put `--extra-snaps` and `--cloud-init` into a separate group, `-o` and `-w` in a separate group, and then let the others just be in the main group.

If you agree, I'm happy to throw something together, including some proposed group names/descriptions.

**Comment by warsaw** [comment]
@vorlonofportland @mvo5 I pushed a change that I think better organizes the options.

```
usage: ubuntu-image [-h] [--version] [-d] [-o FILENAME] [-w DIRECTORY]
                    [--extra-snaps EXTRA_SNAPS] [--cloud-init USER-DATA-FILE]
                    [-c CHANNEL] [-u STEP | -t STEP | -r]
                    [model_assertion]

Generate a bootable disk image.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit

Common options:
  model_assertion       Path to the model assertion file. This argument must
                        be given unless the state machine is being resumed,
                        in which case it cannot be given.
  -d, --debug           Enable debugging output
  -o FILENAME, --output FILENAME
                        The generated disk image file. If not given, the
                        image will be put in a file called disk.img in the
                        working directory (in which case, you probably want
                        to specify -w).
  -w DIRECTORY, --workdir DIRECTORY
                        The working directory in which to download and unpack
                        all the source files for the image. This directory
                        can exist or not, and it is not removed after this
                        program exits. If not given, a temporary working
                        directory is used instead, which *is* deleted after
                        this program exits.

Image contents options:
  Additional options for defining the contents of snap-based images.

  --extra-snaps EXTRA_SNAPS
                        Extra snaps to install. This is passed through to
                        `snap prepare-image`.
  --cloud-init USER-DATA-FILE
                        cloud-config data to be copied to the image
  -c CHANNEL, --channel CHANNEL
                        The snap channel to use

State machine options:
  Options for controlling the internal state machine. These options are
  mutually exclusive. When -u or -t is given, the state machine can be
  resumed later with -r, but -w must be given in that case since the state
  is saved in a .ubuntu-image.pck file in the working directory.

  -u STEP, --until STEP
                        Run the state machine until the given STEP, non-
                        inclusively. STEP can be a name or number.
  -t STEP, --thru STEP  Run the state machine through the given STEP,
                        inclusively. STEP can be a name or number.
  -r, --resume          Continue the state machine from the previously saved
                        state. It is an error if there is no previous state.
```

**Comment by warsaw** [comment]
And of course it all passes locally in a Xenial chroot. :(

**Comment by warsaw** [comment]
It's the snapcraft command that's failing, and this fails in yakkety too.

**Comment by vorlonofportland** [comment]
looks good! can we move the -w option down under the 'state machine options'? won't generally be used outside of that.

**Comment by warsaw** [comment]
@vorlonofportland done!

```
usage: ubuntu-image [-h] [--version] [-d] [-o FILENAME]
                    [--extra-snaps EXTRA_SNAPS] [--cloud-init USER-DATA-FILE]
                    [-c CHANNEL] [-w DIRECTORY] [-u STEP | -t STEP | -r]
                    [model_assertion]

Generate a bootable disk image.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit

Common options:
  model_assertion       Path to the model assertion file. This argument must
                        be given unless the state machine is being resumed,
                        in which case it cannot be given.
  -d, --debug           Enable debugging output
  -o FILENAME, --output FILENAME
                        The generated disk image file. If not given, the
                        image will be put in a file called disk.img in the
                        working directory (in which case, you probably want
                        to specify -w).

Image contents options:
  Additional options for defining the contents of snap-based images.

  --extra-snaps EXTRA_SNAPS
                        Extra snaps to install. This is passed through to
                        `snap prepare-image`.
  --cloud-init USER-DATA-FILE
                        cloud-config data to be copied to the image
  -c CHANNEL, --channel CHANNEL
                        The snap channel to use

State machine options:
  Options for controlling the internal state machine. Other than -w, these
  options are mutually exclusive. When -u or -t is given, the state machine
  can be resumed later with -r, but -w must be given in that case since the
  state is saved in a .ubuntu-image.pck file in the working directory.

  -w DIRECTORY, --workdir DIRECTORY
                        The working directory in which to download and unpack
                        all the source files for the image. This directory
                        can exist or not, and it is not removed after this
                        program exits. If not given, a temporary working
                        directory is used instead, which *is* deleted after
                        this program exits. Use -w if you want to be able to
                        resume a partial state machine run.
  -u STEP, --until STEP
                        Run the state machine until the given STEP, non-
                        inclusively. STEP can be a name or number.
  -t STEP, --thru STEP  Run the state machine through the given STEP,
                        inclusively. STEP can be a name or number.
  -r, --resume          Continue the state machine from the previously saved
                        state. It is an error if there is no previous state.
```

**Pull request merged**
